export const FETCH_SKU = "FETCH_SKU";
export const FETCH_SKU_ERR = "FETCH_SKU_ERR";

export const FETCH_ORGS = "FETCH_ORGS";
export const FETCH_ORGS_ERR = "FETCH_ORGS_ERR";

export const FETCH_ORG = "FETCH_ORG";
export const FETCH_ORG_ERR = "FETCH_ORG_ERR";

export const NEW_ORG = "NEW_ORG";
export const NEW_ORG_ERR = "NEW_ORG_ERR";

export const UPDATE_ORG = "NEW_ORG";
export const UPDATE_ORG_ERR = "UPDATE_ORG_ERR";

export const DELETE_ORG = "DELETE_ORG";
export const DELETE_ORG_ERR = "DELETE_ORG_ERR";

export const ADD_SKU = "ADD_SKU";
export const ADD_SKU_ERR = "ADD_SKU_ERR";

export const DELETE_SKU = "DELETE_SKU";
export const DELETE_SKU_ERR = "DELETE_SKU_ERR";

export const UPDATE_SKU = "UPDATE_SKU";
export const UPDATE_SKU_ERR = "UPDATE_SKU_ERR";

export const ADD_PARAM = "ADD_PARAM";
export const ADD_PARAM_ERR = "ADD_PARAM_ERR";

export const DELETE_PARAM = "ADD_PARAM";
export const DELETE_PARAM_ERR = "ADD_PARAM_ERR";

export const UPDATE_PARAM = "UPDATE_PARAM";
export const UPDATE_PARAM_ERR = "UPDATE_PARAM_ERR";

export const ADD_INSIGHT = "ADD_INSIGHT";
export const ADD_INSIGHT_ERR = "ADD_INSIGHT_ERR";

export const DELETE_INSIGHT = "DELETE_INSIGHT";
export const DELETE_INSIGHT_ERR = "DELETE_INSIGHT_ERR";

export const UPDATE_INSIGHT = "UPDATE_INSIGHT";
export const UPDATE_INSIGHT_ERR = "UPDATE_INSIGHT_ERR";

export const ADD_UPDATE = "ADD_UPDATE";
export const ADD_UPDATE_ERR = "ADD_UPDATE_ERR";

export const UPDATE_UPDATE = "UPDATE_UPDATE";
export const UPDATE_UPDATE_ERR = "UPDATE_UPDATE_ERR";

export const DELETE_UPDATE = "DELETE_UPDATE";
export const DELETE_UPDATE_ERR = "DELETE_UPDATE_ERR";

export const ADD_CUSTOMER = "ADD_CUSTOMER";
export const EDIT_CUSTOMER = "EDIT_CUSTOMER";
export const DELETE_CUSTOMER = "DELETE_CUSTOMER";
export const FETCH_CUSTOMER = "FETCH_CUSTOMER";

export const ADD_CONDITION = "ADD_CONDITION";
export const EDIT_CONDITION = "EDIT_CONDITION";
export const DELETE_CONDITION = "DELETE_CONDITION";

export const ADD_PROMOTION = "ADD_PROMOTION";
export const DELETE_PROMOTION = "DELETE_PROMOTION";
export const EDIT_PROMOTION = "EDIT_PROMOTION";

export const ADD_DEFAULT = "ADD_DEFAULT";
export const ADD_DEFAULT_ERR = "ADD_DEFAULT_ERR";

export const EDIT_DEFAULT = "ADD_DEFAULT";
export const EDIT_DEFAULT_ERR = "ADD_DEFAULT_ERR";

export const DELETE_DEFAULT = "ADD_DEFAULT";
export const DELETE_DEFAULT_ERR = "ADD_DEFAULT_ERR";

export const FETCH_DEFAULT = "FETCH_DEFAULTS";
export const FETCH_DEFAULT_ERR = "FETCH_DEFAULTS_ERR";

export const FETCH_DEFAULTS = "FETCH_DEFAULTS";
export const FETCH_DEFAULTS_ERR = "FETCH_DEFAULTS_ERR";

export const IS_LOADING = "IS_LOADING";
export const IS_LOADING_DEFAULTS = "IS_LOADING_DEFAULTS";
